version: '3.8'

services:
  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase_db
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      MB_DB_HOST: postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabase
      POSTGRES_DB: metabase_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  restore:
    image: postgres:13
    volumes:
      - ./backup/metabase_backup.sql:/backup/metabase_backup.sql
    depends_on:
      - postgres
    entrypoint: ["sh", "-c", "psql -U metabase -d metabase_db -h postgres -f /backup/metabase_backup.sql"]
    environment:
      PGPASSWORD: metabase

volumes:
  pgdata:
