version: '3.8'

services:
  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase_db
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      MB_DB_HOST: postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabase
      POSTGRES_DB: metabase_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  restore:
    image: postgres:13
    depends_on:
      - postgres
    volumes:
      - ./backup/metabase_backup.sql:/backup/metabase_backup.sql
    entrypoint: >
      sh -c "sleep 5 &&
             if [ $(psql -U metabase -h postgres -d metabase_db -tAc 'SELECT COUNT(*) FROM core_user') = '0' ]; then
               echo 'Base vide, restauration en cours...';
               psql -U metabase -h postgres -d metabase_db -f /backup/metabase_backup.sql;
             else
               echo 'Base déjà initialisée, restauration ignorée.';
             fi"
    environment:
      PGPASSWORD: metabase

volumes:
  pgdata:
